input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    remove_field => ["host", "port", "@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "django-logs-%{+YYYY.MM.dd}"
  }
}