input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    remove_field => ["host", "port", "@version"]
  }

  if [level] in ["error", "critical"] {
    mutate { add_field => { "[@metadata][target_index]" => "django-errors" } }
  } else {
    mutate { add_field => { "[@metadata][target_index]" => "django-logs" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "django-logs-%{+YYYY.MM.dd}"
  }
}