{
 "title": "Crypto Analyzer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS по эндпоинтам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (view)(rate(django_http_requests_total_by_view_transport_method_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p50/p95/p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Ошибки 4xx/5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(django_http_responses_total_by_status_total{status=~\"4..|5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB queries / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(django_db_execute_total[5m])",
     "legendFormat": "PostgreSQL"
    }
   ]
  },
  {
   "title": "Cache hit-rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (key_prefix) (rate(crypto_cache_total{result=\"hit\"}[5m])) / sum by (key_prefix) (rate(crypto_cache_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}