# Generated by Django 6.0.3 on 2026-03-30 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinprice',
            options={'verbose_name': 'Цена монеты', 'verbose_name_plural': 'Цены монет'},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={'verbose_name': 'Снимок рынка', 'verbose_name_plural': 'Снимки рынка'},
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='change_24h',
            field=models.FloatField(verbose_name='Изменение (24ч)'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Капитализация'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Цена ($)'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crypto.snapshot', verbose_name='Снимок'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='symbol',
            field=models.CharField(max_length=20, verbose_name='Символ'),
        ),
        migrations.AlterField(
            model_name='coinprice',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Объем (24ч)'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='total_market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=25, verbose_name='Общая капитализация'),
        ),
    ]
