# Generated by Django 6.0.3 on 2026-04-10 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_alter_coinprice_options_alter_snapshot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Символ')),
                ('coin_name', models.CharField(max_length=100, verbose_name='Название')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало отслеживания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Список отслеживаемых монет',
                'verbose_name_plural': 'Списки отслеживаемых монет',
                'ordering': ['-added_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'symbol'), name='unique_symbol_for_user')],
            },
        ),
    ]
