# Generated by Django 6.0.3 on 2026-05-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_balance_portfolio'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_stat_statements;"
        )
    ]
