# Generated by Django 6.0.3 on 2026-05-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_enable_pg_stat_statements'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coinprice',
            index=models.Index(fields=['snapshot', 'symbol'], name='coinprice_snapshot_symbol_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['-created_at'], name='snapshot_created_at_desc_idx'),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX coinprice_upper_symbol_idx ON crypto_coinprice (UPPER(symbol));",
            reverse_sql="DROP INDEX IF EXISTS coinprice_upper_symbol_idx;",
        ),
    ]
